import pandas as pd
df=pd.DataFrame({'Name':['Alice','BOB','charlie','DAVID']})
print("Original DataSet (with inconsistent case formats):")
print(df,"\n")
df['Name_lower']=df['Name'].str.lower()
print("DataSet after converting to lowercase:")
print(df)
df['Name_upper']=df['Name'].str.upper()
print("DataSet after converting to uppercase:")
print(df)